name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/offer-pages || git clone git@github.com:erge-lgtm/deng-lu-ye-.git /home/ubuntu/offer-pages
            git pull origin main
            # 同步所有文件夹
            sudo rsync -av --delete /home/ubuntu/offer-pages/'login-page1' /var/www/html/'login-page1'
            sudo rsync -av --delete /home/ubuntu/offer-pages/'login-page2' /var/www/html/'login-page2'
            for i in {01..20}; do sudo rsync -av --delete /home/ubuntu/offer-pages/folder$i /var/www/html/folder$i; done
            # 更新权限
            sudo chown -R www-data:www-data /var/www/html/'login-page1'
            sudo chown -R www-data:www-data /var/www/html/'login-page2'
            for i in {01..20}; do sudo chown -R www-data:www-data /var/www/html/folder$i; done
            sudo chmod -R 755 /var/www/html/'login-page1'
            sudo chmod -R 755 /var/www/html/'login-page2'
            for i in {01..20}; do sudo chmod -R 755 /var/www/html/folder$i; done
            # 测试并重启 Nginx
            sudo nginx -t
            sudo systemctl restart nginx
